[package]
name = "textautodecode"
description = "Read a text file, automatically detecting text encoding"
version = "1.1.0"
edition = "2024"
authors = ["Pierre Violent"]

[dependencies]
encoding_rs = "0.8"
tempfile = "3.19.1"
