[package]
name = "l08_collections"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
unicode-normalization = "0.1.22"
unicode_categories = "0.1.1"
