[package]
name = "l32b_hardlink"
version = "0.1.0"
description = "Detects hard links on Windows NTFS volumes"
edition = "2024"

[dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO"] }
