[package]
name = "l40_books_dups"
description = "Extract segment from filename"
version = "1.2.1"
authors = ["Pierre Violent"]
edition = "2024"

[dependencies]
myglob = { path = "../../Crates/MyGlob" }
chrono = "0.4.40"
regex = "1.11.1"
unicode-normalization = "0.1.24"
colored = "3.0.0"
